### ISSUE TITLE
Question: why not using `bevy_rapier`?

### ISSUE THREAD

**Issue by azazdeaz** [wynss/kesko#178]
Hi @wynss,

I love this project! You came up with great solutions to get Bevy+Rapier working as a robotics simulator :heart_eyes: 

I was wondering, what are the reasons behind writing a custom `rapier` integration instead of using `bevy_rapier`? Does `bevy_rapier` has some restrictions that prevent from using it in a simulator?

This is probably not the perfect place for questions. Please let me know if i should use another channel.

**Comment by wynss** [comment]
Hi and thanks, glad you enjoyed it!

Very reasonable question. :) The reason is quite simple, when I started to work on Kesko I had not written any Rust so I wanted to get deep into it and become fluent, so my plan was to do everything from scratch. Regarding the physics integration I wanted to try and combine the best of ```bevy_rapier``` and another framework called ```heron```. I've always had in the back of my head that a migration to ```bevy_rapier``` probably makes sense long term so I can focus on more high level features, but when that will happen is very unclear. Recently started a new job so will not have so much time in the near future. Hopefully that will change further down the road.

**Comment by azazdeaz** [comment]
That makes perfect sense, thank you for the answer! :)
